name: Build & Push to DockerHub, Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image to Docker Hub
        run: |
          IMAGE_NAME="yajibola0011/python-application:latest"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy-to-ec2:
    name: SSH Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH and Deploy Python App to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            IMAGE_NAME="yajibola0011/python-application:latest"
            
            echo "Checking Docker installation..."
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing Docker..."
              sudo apt-get update
              sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
              sudo apt-get install -y ca-certificates curl gnupg lsb-release
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io
              sudo usermod -aG docker ubuntu
              sudo systemctl restart docker
              echo "Docker installed."
            else
              echo "Docker is already installed."
            fi

            echo "Waiting for Docker to be ready..."
            until sudo docker info > /dev/null 2>&1; do
              sleep 3
            done

            echo "Logging in to Docker Hub..."
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            echo "Stopping old container if exists..."
            sudo docker stop python-application || true
            sudo docker rm python-application || true

            echo "Pulling latest image: $IMAGE_NAME ..."
            sudo docker pull $IMAGE_NAME

            echo "Running container on port 80..."
            sudo docker run -d --name python-application -p 80:80 $IMAGE_NAME
